# Generated by Django 4.0 on 2022-01-12 09:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainCrew',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('train_number', models.CharField(max_length=32, verbose_name='Numer pociągu')),
                ('date', models.CharField(max_length=32, verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Załoga pociągu',
                'verbose_name_plural': 'Załogi pociągów',
            },
        ),
        migrations.CreateModel(
            name='TrainCrewMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('person', models.CharField(max_length=128, verbose_name='Osoba')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='Telefon')),
                ('profession', models.CharField(max_length=32, verbose_name='Stanowisko')),
                ('start_location', models.CharField(max_length=32, verbose_name='Lokalizacja początkowa')),
                ('end_location', models.CharField(max_length=32, verbose_name='Lokalizacja końcowa')),
                ('crew', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='crews.traincrew', verbose_name='Członek załogi')),
            ],
            options={
                'verbose_name': 'Członek załogi pociągu',
                'verbose_name_plural': 'Członkowie załogi pociągów',
            },
        ),
    ]
