# Generated by Django 4.0 on 2022-01-13 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traincrew',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Ostatnia aktualizacja'),
        ),
    ]
