# Generated by Django 4.0 on 2022-01-12 09:16

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import utils.icals
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, verbose_name='Numer')),
                ('carrier', models.CharField(blank=True, max_length=64, null=True, verbose_name='Przewoźnik')),
                ('departure_date', models.DateTimeField(verbose_name='Czas odjazdu')),
                ('departure_station', models.CharField(max_length=64, verbose_name='Odjazd ze stacji')),
                ('departure_platform', models.CharField(max_length=32, verbose_name='Odjazd z peronu')),
                ('arrival_date', models.DateTimeField(verbose_name='Czas przyjazdu')),
                ('arrival_station', models.CharField(max_length=64, verbose_name='Przyjazd na stację')),
                ('arrival_platform', models.CharField(max_length=32, verbose_name='Przyjazd na peron')),
            ],
            options={
                'verbose_name': 'Pociąg',
                'verbose_name_plural': 'Pociągi',
            },
            bases=(models.Model, utils.icals.ICalComponentable),
        ),
        migrations.CreateModel(
            name='VerifiedStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Nazwa')),
            ],
            options={
                'verbose_name': 'Zweryfikowana stacja',
                'verbose_name_plural': 'Zweryfikowane stacje',
            },
        ),
        migrations.CreateModel(
            name='RailroadAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('homeplace', models.CharField(max_length=64, verbose_name='Stacja kolejowa w miejscu zamieszkania')),
                ('workplace', models.CharField(max_length=64, verbose_name='Stacja kolejowa w miejscu pracy')),
                ('administration_time', models.PositiveIntegerField(choices=[(10, '10 minut'), (20, '20 minut'), (30, '30 minut'), (40, '40 minut'), (50, '50 minut'), (60, '60 minut')], default=10, verbose_name='Czas administracyjny')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='railroad_account', to='users.user', verbose_name='Konto kolejowe')),
            ],
            options={
                'verbose_name': 'Konto kolejowe',
                'verbose_name_plural': 'Konta kolejowe',
            },
        ),
        migrations.AddConstraint(
            model_name='railroadaccount',
            constraint=models.CheckConstraint(check=models.Q(('homeplace__iexact', django.db.models.expressions.F('workplace')), _negated=True), name='homeplace_not_eq_workplace'),
        ),
    ]
