# Generated by Django 3.2.9 on 2021-12-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railroads', '0003_railroadaccount_spare_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railroadaccount',
            name='administration_time',
            field=models.PositiveIntegerField(choices=[(15, '15 minut'), (30, '30 minut'), (45, '45 minut'), (60, '60 minut')], default=15, verbose_name='Czas dojścia ze stacji'),
        ),
    ]
