# Generated by Django 3.2.9 on 2021-11-30 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RailroadStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nazwa stacji kolejowej')),
            ],
            options={
                'verbose_name': 'Stacja kolejowa',
                'verbose_name_plural': 'Stacje kolejowe',
            },
        ),
        migrations.CreateModel(
            name='RailroadAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ostatnia aktualizacja')),
                ('homeplace', models.CharField(max_length=64, verbose_name='Stacja kolejowa w miejscu zamieszkania')),
                ('workplace', models.CharField(max_length=64, verbose_name='Stacja kolejowa w miejscu pracy')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='railroad_account', to=settings.AUTH_USER_MODEL, verbose_name='Konto kolejowe')),
            ],
            options={
                'verbose_name': 'Konto kolejowe użytkownika',
                'verbose_name_plural': 'Konta kolejowe użytkowników',
            },
        ),
        migrations.AddConstraint(
            model_name='railroadaccount',
            constraint=models.CheckConstraint(check=models.Q(('homeplace__iexact', django.db.models.expressions.F('workplace')), _negated=True), name='homeplace_not_eq_workplace'),
        ),
    ]
