# Generated by Django 3.2.9 on 2021-12-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railroads', '0002_alter_railroadstation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='railroadaccount',
            name='spare_time',
            field=models.PositiveIntegerField(choices=[(15, '15 minut'), (30, '30 minut'), (45, '45 minut'), (60, '60 minut')], default=15, verbose_name='Czas dojścia'),
        ),
    ]
