# Generated by Django 3.2.9 on 2021-12-03 12:37

from django.db import migrations, models
import django.db.models.deletion
import utils.icals


class Migration(migrations.Migration):

    dependencies = [
        ('railroads', '0004_alter_railroadaccount_spare_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='RailroadWaypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=64, verbose_name='Stacja')),
                ('platform', models.CharField(max_length=32, verbose_name='Peron')),
                ('date', models.DateTimeField(verbose_name='Data i czas')),
            ],
            options={
                'verbose_name': 'Kolejowy punkt trasy',
                'verbose_name_plural': 'Kolejowe punkty trasy',
            },
        ),
        migrations.AlterField(
            model_name='railroadaccount',
            name='spare_time',
            field=models.PositiveIntegerField(choices=[(15, '15 minut'), (30, '30 minut'), (45, '45 minut'), (60, '60 minut')], default=15, verbose_name='Czas dojścia ze stacji kolejowej'),
        ),
        migrations.CreateModel(
            name='PublicRailroadTrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, verbose_name='Numer')),
                ('carrier', models.CharField(blank=True, max_length=64, null=True, verbose_name='Przewoźnik')),
                ('end_waypoint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='end_waypoint', to='railroads.railroadwaypoint', verbose_name='Końcowy punkt trasy')),
                ('start_waypoint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='start_waypoint', to='railroads.railroadwaypoint', verbose_name='Początkowy punkt trasy')),
            ],
            options={
                'verbose_name': 'Publiczny pociąg',
                'verbose_name_plural': 'Publiczne pociągi',
            },
            bases=(models.Model, utils.icals.ICalComponentable),
        ),
    ]
