# Generated by Django 3.2.9 on 2021-12-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railroads', '0005_auto_20211203_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='railroadwaypoint',
            name='date',
        ),
        migrations.AddField(
            model_name='publicrailroadtrain',
            name='arrival_date',
            field=models.DateTimeField(default=None, verbose_name='Przyjazd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicrailroadtrain',
            name='departure_date',
            field=models.DateTimeField(default=None, verbose_name='Odjazd'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='railroadaccount',
            name='spare_time',
            field=models.PositiveIntegerField(choices=[(15, '15 minut'), (20, '20 minut'), (30, '30 minut'), (45, '45 minut'), (60, '60 minut')], default=20, verbose_name='Czas dojścia ze stacji kolejowej'),
        ),
    ]
