# Generated by Django 3.2.9 on 2021-12-03 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('railroads', '0006_auto_20211203_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicrailroadtrain',
            name='end_waypoint',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_waypoint', to='railroads.railroadwaypoint', verbose_name='Końcowy punkt trasy'),
        ),
        migrations.AlterField(
            model_name='publicrailroadtrain',
            name='start_waypoint',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_waypoint', to='railroads.railroadwaypoint', verbose_name='Początkowy punkt trasy'),
        ),
    ]
