# Generated by Django 3.2.9 on 2021-12-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railroads', '0007_auto_20211203_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicrailroadtrain',
            name='end_waypoint',
        ),
        migrations.RemoveField(
            model_name='publicrailroadtrain',
            name='start_waypoint',
        ),
        migrations.AddField(
            model_name='publicrailroadtrain',
            name='arrival_platform',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Przyjazd na peron'),
        ),
        migrations.AddField(
            model_name='publicrailroadtrain',
            name='arrival_station',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Przyjazd na stację'),
        ),
        migrations.AddField(
            model_name='publicrailroadtrain',
            name='departure_platform',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Odjazd z peronu'),
        ),
        migrations.AddField(
            model_name='publicrailroadtrain',
            name='departure_station',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Odjazd ze stacji'),
        ),
        migrations.AlterField(
            model_name='publicrailroadtrain',
            name='arrival_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Czas przyjazdu'),
        ),
        migrations.AlterField(
            model_name='publicrailroadtrain',
            name='departure_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Czas odjazdu'),
        ),
        migrations.AlterField(
            model_name='publicrailroadtrain',
            name='number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Numer'),
        ),
        migrations.DeleteModel(
            name='RailroadWaypoint',
        ),
    ]
