# Generated by Django 3.2.9 on 2021-12-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railroads', '0009_auto_20211204_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railroadaccount',
            name='spare_time',
            field=models.PositiveIntegerField(choices=[(10, '10 minut'), (20, '20 minut'), (30, '30 minut'), (40, '40 minut'), (50, '50 minut'), (60, '60 minut')], default=10, verbose_name='Czas dojścia ze stacji kolejowej'),
        ),
    ]
