# Generated by Django 4.0 on 2021-12-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railroads', '0010_alter_railroadaccount_spare_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railroadaccount',
            name='spare_time',
            field=models.PositiveIntegerField(choices=[(10, '10 minut'), (20, '20 minut'), (30, '30 minut'), (40, '40 minut'), (50, '50 minut'), (60, '60 minut')], default=10, verbose_name='Czas dojścia pieszo'),
        ),
    ]
