# Generated by Django 3.2.9 on 2021-11-25 09:46

import uuid

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_updated',
                 models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ostatnia aktualizacja')),
                ('title', models.CharField(max_length=32, verbose_name='Tytuł')),
                ('start_date', models.DateTimeField(verbose_name='Data rozpoczęcia')),
                ('end_date', models.DateTimeField(verbose_name='Data zakończenia')),
            ],
            options={
                'verbose_name': 'Służba',
                'verbose_name_plural': 'Służby',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainCrew',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_updated',
                 models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ostatnia aktualizacja')),
                ('train_number', models.CharField(max_length=32, verbose_name='Numer pociągu')),
                ('date', models.DateTimeField(verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Załoga pociągu',
                'verbose_name_plural': 'Załogi pociągów',
            },
        ),
        migrations.CreateModel(
            name='TrainCrewMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_updated',
                 models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ostatnia aktualizacja')),
                ('person', models.CharField(max_length=128, verbose_name='Osoba')),
                ('phone_number', models.CharField(max_length=32, verbose_name='Numer telefonu')),
                ('profession', models.CharField(max_length=32, verbose_name='Stanowisko')),
                ('start_location', models.CharField(max_length=32, verbose_name='Lokalizacja początkowa')),
                ('end_location', models.CharField(max_length=32, verbose_name='Lokalizacja końcowa')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='members',
                                           to='alina.traincrew', verbose_name='Członek załogi')),
            ],
            options={
                'verbose_name': 'Członek załogi pociągu',
                'verbose_name_plural': 'Członkowie załogi pociągu',
            },
        ),
        migrations.CreateModel(
            name='AllocationTimetable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_updated',
                 models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ostatnia aktualizacja')),
                ('month', models.PositiveIntegerField(
                    choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'),
                             (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'),
                             (12, 'December')], default=11, verbose_name='Miesiąc')),
                ('year', models.PositiveIntegerField(choices=[(2021, '2021'), (2022, '2022')], default=2021,
                                                     verbose_name='Rok')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           related_query_name='timetables', to=settings.AUTH_USER_MODEL,
                                           verbose_name='Plan służb')),
            ],
            options={
                'verbose_name': 'Plan Służb',
                'verbose_name_plural': 'Plany Służb',
            },
        ),
        migrations.CreateModel(
            name='AllocationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=32, verbose_name='Number pociągu')),
                ('action', models.CharField(max_length=128, verbose_name='Akcja')),
                ('start_location', models.CharField(max_length=128, verbose_name='Lokalizacja początkowa')),
                ('start_hour', models.CharField(max_length=32, verbose_name='Godzina')),
                ('end_location', models.CharField(max_length=128, verbose_name='lokalizacja końcowa')),
                ('end_hour', models.CharField(max_length=32, verbose_name='Godzina')),
                ('allocation',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='details',
                                   to='alina.allocation', verbose_name='Detal służby')),
            ],
            options={
                'verbose_name': 'Detail służby',
                'verbose_name_plural': 'Detale służb',
            },
        ),
        migrations.AddField(
            model_name='allocation',
            name='timetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_query_name='timetables', to='alina.allocationtimetable',
                                    verbose_name='Służba'),
        ),
        migrations.AddConstraint(
            model_name='allocationtimetable',
            constraint=models.CheckConstraint(check=models.Q(('month__lte', 12)), name='month_lte_12'),
        ),
        migrations.AddConstraint(
            model_name='allocationtimetable',
            constraint=models.UniqueConstraint(fields=('user_id', 'month', 'year'),
                                               name='unique_user_allocation_timetable'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.CheckConstraint(
                check=models.Q(('end_date__lte', django.db.models.expressions.F('start_date'))),
                name='end_date_lte_start_date_check'),
        ),
    ]
