# Generated by Django 3.2.9 on 2021-11-25 09:52

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('alina', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='allocation',
            name='end_date_lte_start_date_check',
        ),
        migrations.AlterField(
            model_name='traincrewmember',
            name='crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='members', to='alina.traincrew', verbose_name='Członek załogi'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', django.db.models.expressions.F('start_date'))), name='end_date_lte_start_date_check'),
        ),
    ]
