# Generated by Django 3.2.9 on 2021-11-25 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alina', '0002_auto_20211125_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='timetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='alina.allocationtimetable'),
        ),
        migrations.AlterField(
            model_name='allocationdetail',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alina.allocation'),
        ),
        migrations.AlterField(
            model_name='allocationtimetable',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
