# Generated by Django 3.2.9 on 2021-11-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('alina', '0005_auto_20211125_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationdetail',
            name='date_of_action',
            field=models.CharField(max_length=32, null=True, verbose_name='Data akcji'),
        ),
    ]
