# Generated by Django 3.2.9 on 2021-11-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alina', '0006_allocationdetail_date_of_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allocationdetail',
            options={'ordering': ['action_date'], 'verbose_name': 'Detail służby', 'verbose_name_plural': 'Detale służb'},
        ),
        migrations.RemoveField(
            model_name='allocationdetail',
            name='date_of_action',
        ),
        migrations.AddField(
            model_name='allocationdetail',
            name='action_date',
            field=models.DateTimeField(null=True, verbose_name='Data akcji'),
        ),
    ]
