# Generated by Django 3.2.9 on 2021-11-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alina', '0008_alter_traincrew_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traincrewmember',
            options={'verbose_name': 'Członek załogi pociągu', 'verbose_name_plural': 'Członkowie załogi pociągów'},
        ),
        migrations.AlterField(
            model_name='allocationdetail',
            name='end_location',
            field=models.CharField(max_length=128, null=True, verbose_name='Lokalizacja końcowa'),
        ),
    ]
