# Generated by Django 3.2.9 on 2021-11-29 22:17

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('alina', '0009_auto_20211129_2221'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='allocationtimetable',
            managers=[
                ('caldav', django.db.models.manager.Manager()),
            ],
        ),
    ]
