# Generated by Django 3.2.9 on 2021-12-03 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('railroads', '0005_auto_20211203_1337'),
        ('alina', '0011_auto_20211130_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationtimetable',
            name='month',
            field=models.PositiveIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=12, verbose_name='Miesiąc'),
        ),
        migrations.CreateModel(
            name='AllocationTrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='after', to='railroads.publicrailroadtrain', verbose_name='Pociąg po służbie')),
                ('allocation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='train', to='alina.allocation', verbose_name='Pociąg dla służby')),
                ('before', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='before', to='railroads.publicrailroadtrain', verbose_name='Pociąg przed służbą')),
            ],
            options={
                'verbose_name': 'Pociąg dla służby',
                'verbose_name_plural': 'Pociągi dla służb',
            },
        ),
    ]
