# Generated by Django 4.0 on 2021-12-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alina', '0012_auto_20211203_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traincrewmember',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Numer telefonu'),
        ),
    ]
