# Generated by Django 4.0 on 2022-01-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alina', '0013_alter_traincrewmember_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationtimetable',
            name='month',
            field=models.PositiveIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1, verbose_name='Miesiąc'),
        ),
        migrations.AlterField(
            model_name='allocationtimetable',
            name='year',
            field=models.PositiveIntegerField(choices=[(2022, '2022'), (2023, '2023')], default=2022, verbose_name='Rok'),
        ),
    ]
