# Generated by Django 4.0 on 2022-01-12 09:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalDAVAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128, verbose_name='Login')),
                ('password', models.CharField(max_length=128, verbose_name='Hasło')),
                ('url', models.URLField(verbose_name='Adres URL')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caldav_account', to='users.user', verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Konto CalDAV',
                'verbose_name_plural': 'Konta CalDAV',
            },
        ),
    ]
