# Generated by Django 3.2.9 on 2021-11-29 21:21

import uuid

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalDAVAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ostatnia aktualizacja')),
                ('username', models.CharField(max_length=128, verbose_name='Login użytkownika')),
                ('password', models.CharField(max_length=128, verbose_name='Hasło użytkownika')),
                ('url', models.URLField(verbose_name='Adres URL Serwera CalDAV')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caldav_profile', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Konto CalDAV',
                'verbose_name_plural': 'Konta CalDAV',
            },
        ),
    ]
