# Generated by Django 3.2.9 on 2021-11-29 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caldavs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caldavaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caldav_account', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
    ]
