# Generated by Django 4.0 on 2021-12-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caldavs', '0002_alter_caldavaccount_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caldavaccount',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Hasło'),
        ),
        migrations.AlterField(
            model_name='caldavaccount',
            name='url',
            field=models.URLField(verbose_name='Adres URL'),
        ),
        migrations.AlterField(
            model_name='caldavaccount',
            name='username',
            field=models.CharField(max_length=128, verbose_name='Login'),
        ),
    ]
