# Generated by Django 4.0 on 2021-12-21 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketProlongation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(choices=[('Wezwanie do zapłaty', 'Fine'), ('Blankietowy', 'Blanket'), ('Zastępczy', 'Replacement')], default='Wezwanie do zapłaty', max_length=128, verbose_name='Bilet')),
                ('last_renewal_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data ostatniego przedłużenia')),
                ('expiration_date', models.DateField(blank=True, editable=False, null=True, verbose_name='Data wygaśnięcia')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Prolongata Biletu',
                'verbose_name_plural': 'Prolongaty Biletów',
            },
        ),
        migrations.AddConstraint(
            model_name='ticketprolongation',
            constraint=models.UniqueConstraint(fields=('user_id', 'ticket'), name='unique_user_ticket_prolongation'),
        ),
    ]
