# Generated by Django 4.0 on 2021-12-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prolongations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketprolongation',
            name='ticket',
            field=models.CharField(choices=[('Wezwanie do zapłaty', 'FINE'), ('Blankietowy', 'BLANKET'), ('Zastępczy', 'REPLACEMENT')], default='Wezwanie do zapłaty', max_length=128, verbose_name='Bilet'),
        ),
    ]
