# Generated by Django 4.0 on 2022-01-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prolongations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prolongation',
            name='ticket',
            field=models.CharField(choices=[('FINE', 'Wezwania do zapłaty'), ('BLANKET', 'Bilety blankietowe')], default='FINE', max_length=128, verbose_name='Bilety'),
        ),
    ]
