# Generated by Django 4.0 on 2021-12-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prolongations', '0002_alter_ticketprolongation_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketprolongation',
            name='ticket',
            field=models.CharField(choices=[('FINE', 'Wezwanie do zapłaty'), ('BLANKET', 'Blankietowy'), ('REPLACEMENT', 'Zastępczy')], default='FINE', max_length=128, verbose_name='Bilet'),
        ),
    ]
