# Generated by Django 4.0 on 2021-12-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prolongations', '0003_alter_ticketprolongation_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketprolongation',
            name='ticket',
            field=models.CharField(choices=[('FINE', 'Wezwania do zapłaty'), ('BLANKET', 'Bilety blankietowe'), ('REPLACEMENT', 'Bilety zastępcze')], default='FINE', max_length=128, verbose_name='Bilety'),
        ),
    ]
