# Generated by Django 4.0 on 2022-01-16 17:06

from django.db import migrations, models
import django.utils.timezone
import common.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', common.fields.LowerCaseCharField(max_length=128, verbose_name='Nazwa punktu')),
            ],
            options={
                'verbose_name': 'Punkt na szlaku',
                'verbose_name_plural': 'Punkty na szlaku',
            },
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=128, verbose_name='Początek szlaku')),
                ('end', models.CharField(max_length=128, verbose_name='Koniec szlaku')),
                ('last_driven', models.DateField(default=django.utils.timezone.now, verbose_name='Ostatniego przejazdu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Użytkownik')),
                ('waypoints', models.ManyToManyField(blank=True, related_name='waypoints', to='trails.Waypoint', verbose_name='Punkty na szlaku')),
            ],
            options={
                'verbose_name': 'Szlak',
                'verbose_name_plural': 'Szlaki',
            },
        ),
        migrations.AddConstraint(
            model_name='trail',
            constraint=models.CheckConstraint(check=models.Q(('start', django.db.models.expressions.F('end')), _negated=True), name='trail_start_cannot_be_equal_end'),
        ),
    ]
