# Generated by Django 4.0 on 2022-01-08 15:03

from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailstation',
            name='name',
            field=utils.fields.LowercaseCharField(max_length=128, verbose_name='Nazwa stacji'),
        ),
    ]
