# Generated by Django 4.0 on 2022-01-16 17:13

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0002_remove_trail_trail_start_cannot_be_equal_end_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trail',
            name='trail_start_cannot_be_equal_end',
        ),
        migrations.AddConstraint(
            model_name='trail',
            constraint=models.CheckConstraint(check=models.Q(('start', django.db.models.expressions.F('end')), _negated=True), name='trail_start_cannot_be_equal_end'),
        ),
    ]
