# Generated by Django 4.0 on 2022-01-16 17:53

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import re
import common.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0003_remove_trail_trail_start_cannot_be_equal_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='end',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9äöüÄÖÜ]*$'), code='invalid', message='Wpisz poprawną nazwę')], verbose_name='Stacja końcowa'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='last_driven',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data ostatniego przejazdu'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='start',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9äöüÄÖÜ]*$'), code='invalid', message='Wpisz poprawną nazwę')], verbose_name='Stacja początkowa'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='name',
            field=common.fields.LowerCaseCharField(max_length=128, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9äöüÄÖÜ]*$'), code='invalid', message='Wpisz poprawną nazwę')], verbose_name='Nazwa'),
        ),
    ]
