# Generated by Django 4.0 on 2022-01-18 20:27

import common.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0004_alter_trail_end_alter_trail_last_driven_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='waypoints',
        ),
        migrations.AddField(
            model_name='waypoint',
            name='trail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='trails.trail', verbose_name='Szlak'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='end',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9äöüÄÖÜaąćęłńóśźż ]*$'), code='invalid', message='Wpisz poprawną nazwę')], verbose_name='Stacja końcowa'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='start',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9äöüÄÖÜaąćęłńóśźż ]*$'), code='invalid', message='Wpisz poprawną nazwę')], verbose_name='Stacja początkowa'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='name',
            field=common.fields.LowerCaseCharField(max_length=128, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9äöüÄÖÜaąćęłńóśźż ]*$'), code='invalid', message='Wpisz poprawną nazwę')], verbose_name='Nazwa'),
        ),
    ]
