# Generated by Django 4.0 on 2022-01-18 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0006_remove_waypoint_trail_trail_waypoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='waypoints',
        ),
        migrations.AddField(
            model_name='waypoint',
            name='trail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='trails.trail', verbose_name='Stacje na szlaku'),
        ),
    ]
