# Generated by Django 4.0 on 2022-01-19 15:44

import common.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0007_remove_trail_waypoints_waypoint_trail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='end',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9äöüÄÖÜaąćęłńóśźż ]*$'), code='invalid', message='Wpisz poprawną nazwę - nazwa nie może zawierać specjalnych znaków')], verbose_name='Stacja końcowa'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='start',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9äöüÄÖÜaąćęłńóśźż ]*$'), code='invalid', message='Wpisz poprawną nazwę - nazwa nie może zawierać specjalnych znaków')], verbose_name='Stacja początkowa'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='name',
            field=common.fields.LowerCaseCharField(max_length=128, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9äöüÄÖÜaąćęłńóśźż ]*$'), code='invalid', message='Wpisz poprawną nazwę - nazwa nie może zawierać specjalnych znaków')], verbose_name='Stacja'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='trail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='trails.trail', unique=True, verbose_name='Punkt'),
        ),
    ]
