# Generated by Django 4.0 on 2022-01-19 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0008_alter_trail_end_alter_trail_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waypoint',
            name='trail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='trails.trail', verbose_name='Punkt'),
        ),
    ]
