# Generated by Django 4.0 on 2022-01-12 09:16

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import utils.icals
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetables', '__first__'),
        ('trains', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Ostatnia aktualizacja')),
                ('title', models.CharField(max_length=32, verbose_name='Tytuł')),
                ('signature', models.CharField(max_length=64, verbose_name='Sygnatura')),
                ('start_date', models.DateTimeField(verbose_name='Rozpoczęcie')),
                ('end_date', models.DateTimeField(verbose_name='Zakończenie')),
                ('timetable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='timetables.timetable', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Służba',
                'verbose_name_plural': 'Służby',
                'ordering': ['start_date'],
            },
            bases=(models.Model, utils.icals.ICalComponentable),
        ),
        migrations.CreateModel(
            name='AllocationTrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='after', to='trains.train', verbose_name='Po')),
                ('allocation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='train', to='allocations.allocation', verbose_name='Pociąg dla służby')),
                ('before', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='before', to='trains.train', verbose_name='Przed')),
            ],
            options={
                'verbose_name': 'Pociąg dla służby',
                'verbose_name_plural': 'Pociągi dla służb',
            },
        ),
        migrations.CreateModel(
            name='AllocationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=32, null=True, verbose_name='Numer pociągu')),
                ('date', models.DateTimeField(null=True, verbose_name='Data')),
                ('name', models.CharField(max_length=128, null=True, verbose_name='Nazwa')),
                ('start_location', models.CharField(max_length=128, null=True, verbose_name='Lokalizacja początkowa')),
                ('start_hour', models.CharField(max_length=32, null=True, verbose_name='Godzina')),
                ('end_location', models.CharField(max_length=128, null=True, verbose_name='Lokalizacja końcowa')),
                ('end_hour', models.CharField(max_length=32, null=True, verbose_name='Godzina')),
                ('allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='allocations.allocation', verbose_name='Służba')),
            ],
            options={
                'verbose_name': 'Akcja',
                'verbose_name_plural': 'Akcje',
                'ordering': ['date'],
            },
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', django.db.models.expressions.F('start_date'))), name='check_end_date_lte_start_date'),
        ),
    ]
