# Generated by Django 4.0 on 2022-01-21 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='signature',
        ),
    ]
