# Generated by Django 4.0 on 2022-01-08 15:03

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import utils.icals
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('railroads', '0011_alter_railroadaccount_spare_time'),
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ostatnia aktualizacja')),
                ('title', models.CharField(max_length=32, verbose_name='Tytuł')),
                ('start_date', models.DateTimeField(verbose_name='Data rozpoczęcia')),
                ('end_date', models.DateTimeField(verbose_name='Data zakończenia')),
            ],
            options={
                'verbose_name': 'Służba',
                'verbose_name_plural': 'Służby',
                'ordering': ['start_date'],
            },
            bases=(models.Model, utils.icals.ICalComponentable),
        ),
        migrations.CreateModel(
            name='TrainCrew',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ostatnia aktualizacja')),
                ('train_number', models.CharField(max_length=32, verbose_name='Numer pociągu')),
                ('date', models.CharField(max_length=32, verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Załoga pociągu',
                'verbose_name_plural': 'Załogi pociągów',
            },
        ),
        migrations.CreateModel(
            name='TrainCrewMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ostatnia aktualizacja')),
                ('person', models.CharField(max_length=128, verbose_name='Osoba')),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='Numer telefonu')),
                ('profession', models.CharField(max_length=32, verbose_name='Stanowisko')),
                ('start_location', models.CharField(max_length=32, verbose_name='Lokalizacja początkowa')),
                ('end_location', models.CharField(max_length=32, verbose_name='Lokalizacja końcowa')),
                ('crew', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='members', to='scrapers.traincrew', verbose_name='Członek załogi')),
            ],
            options={
                'verbose_name': 'Członek załogi pociągu',
                'verbose_name_plural': 'Członkowie załogi pociągów',
            },
        ),
        migrations.CreateModel(
            name='AllocationTrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='after', to='railroads.publicrailroadtrain', verbose_name='Pociąg po służbie')),
                ('allocation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='train', to='scrapers.allocation', verbose_name='Pociąg dla służby')),
                ('before', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='before', to='railroads.publicrailroadtrain', verbose_name='Pociąg przed służbą')),
            ],
            options={
                'verbose_name': 'Pociąg dla służby',
                'verbose_name_plural': 'Pociągi dla służb',
            },
        ),
        migrations.CreateModel(
            name='AllocationTimetable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ostatnia aktualizacja')),
                ('month', models.PositiveIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1, verbose_name='Miesiąc')),
                ('year', models.PositiveIntegerField(choices=[(2022, '2022'), (2023, '2023')], default=2022, verbose_name='Rok')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Plan Służb',
                'verbose_name_plural': 'Plany Służb',
            },
        ),
        migrations.CreateModel(
            name='AllocationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=32, null=True, verbose_name='Numer pociągu')),
                ('action_date', models.DateTimeField(null=True, verbose_name='Data akcji')),
                ('action', models.CharField(max_length=128, null=True, verbose_name='Akcja')),
                ('start_location', models.CharField(max_length=128, null=True, verbose_name='Lokalizacja początkowa')),
                ('start_hour', models.CharField(max_length=32, null=True, verbose_name='Godzina')),
                ('end_location', models.CharField(max_length=128, null=True, verbose_name='Lokalizacja końcowa')),
                ('end_hour', models.CharField(max_length=32, null=True, verbose_name='Godzina')),
                ('allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapers.allocation', verbose_name='Służba')),
            ],
            options={
                'verbose_name': 'Detail służby',
                'verbose_name_plural': 'Detale służb',
                'ordering': ['action_date'],
            },
        ),
        migrations.AddField(
            model_name='allocation',
            name='timetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapers.allocationtimetable', verbose_name='Plan służb'),
        ),
        migrations.AddConstraint(
            model_name='allocationtimetable',
            constraint=models.CheckConstraint(check=models.Q(('month__lte', 12)), name='month_lte_12'),
        ),
        migrations.AddConstraint(
            model_name='allocationtimetable',
            constraint=models.UniqueConstraint(fields=('user_id', 'month', 'year'), name='unique_user_allocation_timetable'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', django.db.models.expressions.F('start_date'))), name='end_date_lte_start_date_check'),
        ),
    ]
