# Generated by Django 4.0 on 2022-01-12 09:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Ostatnia aktualizacja')),
                ('month', models.PositiveIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1, verbose_name='Miesiąc')),
                ('year', models.PositiveIntegerField(choices=[(2022, '2022'), (2023, '2023')], default=2022, verbose_name='Rok')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plany',
            },
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.CheckConstraint(check=models.Q(('month__lte', 12)), name='month_lte_12'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('user_id', 'month', 'year'), name='unique_allocation_timetable_for_user'),
        ),
    ]
